AWSTemplateFormatVersion: "2010-09-09"
Description: FCPL account access
Parameters:
    FCPLAccountId:
        Type: String
        AllowedPattern: "^[0-9]+$"
    FCPLPassword:
        Type: String
        NoEcho: true
    S3Bucket:
        Type: String
    MaxCacheAgeHours:
        Type: Number
        Default: 10
    BackgroundRenewIntervalHours:
        Type: Number
        Default: 12
    NotificationEmail:
        Type: String
        Default: 'your@email.com'
Resources:
    UserPool:
        Type: "AWS::Cognito::UserPool"
        Properties:
            AdminCreateUserConfig:
                InviteMessageTemplate:
                    EmailMessage: 'PisoMojado welcomes you to the easier way to use the Fairfax County Public Library.  Your username is {username}, and your verification code is {####}.  Have fun!'
                    EmailSubject: "Welcome to the easier way to use FCPL!  from PisoMojado"
            AliasAttributes:
                - email
            AutoVerifiedAttributes:
                - email
            EmailVerificationMessage: 'Your username is {username}, and your verification code is {####}.  Have fun!'
            EmailVerificationSubject: "Email verification for the easier way to use FCPL (from PisoMojado)"
            Policies:
                PasswordPolicy:
                    MinimumLength: 6
                    RequireLowercase: false
                    RequireNumbers: false
                    RequireSymbols: false
                    RequireUppercase: false
            UserPoolName: pisomojado-fcpl-user-pool
    UserPoolClient:
        Type: "AWS::Cognito::UserPoolClient"
        Properties:
            UserPoolId: !Ref UserPool
    IdentityPool:
        Type: "AWS::Cognito::IdentityPool"
        Properties:
            AllowUnauthenticatedIdentities: false
            CognitoIdentityProviders:
                - ClientId: !Ref UserPoolClient
                  ProviderName: !GetAtt UserPool.ProviderName
                  ServerSideTokenCheck: true
    IdentityPoolRoleAttachmentMapping:
        Type: Custom::DynamicMapTransform
        Properties:
            ServiceToken: !ImportValue DynamicMapTransformer
            AttributeName: IdentityPoolRoleMappings
            Entries:
                - Key: !Sub ${UserPool.ProviderName}:${UserPoolClient}
                  Value:
                    Type: Token
                    AmbiguousRoleResolution: AuthenticatedRole
    IdentityPoolRoleAttachment:
        Type: "AWS::Cognito::IdentityPoolRoleAttachment"
        Properties:
            IdentityPoolId: !Ref IdentityPool
            RoleMappings: !GetAtt IdentityPoolRoleAttachmentMapping.IdentityPoolRoleMappings
            Roles:
                authenticated: !GetAtt IdentityPoolAuthenticatedRole.Arn
                unauthenticated: !GetAtt IdentityPoolUnauthenticatedRole.Arn
    IdentityPoolAuthenticatedRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Federated:
                            - "cognito-identity.amazonaws.com"
                      Action: "sts:AssumeRole"
                      Condition:
                        StringEquals:
                            "cognito-identity.amazonaws.com:aud": !Ref UserPool
                        "ForAnyValue:StringLike":
                            "cognito-identity.amazonaws.com:amr": "authenticated"
            Policies:
                - PolicyName: APIAccess
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Effect: Allow
                          Action:
                            - "execute-api:Invoke"        
                          Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FcplApi}/${FcplApiStage}/*"
    IdentityPoolUnauthenticatedRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Federated:
                            - "cognito-identity.amazonaws.com"
                      Action: "sts:AssumeRole"
                      Condition:
                        StringEquals:
                            "cognito-identity.amazonaws.com:aud": !Ref UserPool
                        "ForAnyValue:StringLike":
                            "cognito-identity.amazonaws.com:amr": "unauthenticated"
    UserTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                - AttributeName: IdentityId
                  AttributeType: S
            KeySchema:
                - AttributeName: IdentityId
                  KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
    FcplApi:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Description: FCPL API
            Name: "fcpl-api"
    FcplApiBooksResource:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref FcplApi
            ParentId: !GetAtt FcplApi.RootResourceId
            PathPart: books
    FcplApiBooksGet:
        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref FcplApi
            ResourceId: !Ref FcplApiBooksResource
            HttpMethod: GET
            AuthorizationType: NONE
            RequestParameters:
                "method.request.querystring.forceRefresh": false
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetBooksFunction.Arn}/invocations
    FcplApiBooksOptions:
        Type: "AWS::ApiGateway::Method"
        Properties:
            AuthorizationType: NONE
            RestApiId: !Ref FcplApi
            ResourceId: !Ref FcplApiBooksResource
            HttpMethod: OPTIONS
            Integration:
                IntegrationResponses:
                    - StatusCode: 200
                      ResponseParameters:
                        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                        method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                      ResponseTemplates:
                        application/json: ''
                PassthroughBehavior: WHEN_NO_MATCH
                RequestTemplates:
                    application/json: '{"statusCode": 200}'
                Type: MOCK
            MethodResponses:
                - StatusCode: 200
                  ResponseModels:
                    application/json: 'Empty'
                  ResponseParameters:
                    method.response.header.Access-Control-Allow-Headers: false
                    method.response.header.Access-Control-Allow-Methods: false
                    method.response.header.Access-Control-Allow-Origin: false
    FcplApiUserResource:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref FcplApi
            ParentId: !GetAtt FcplApi.RootResourceId
            PathPart: user
    FcplApiUserGet:
        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref FcplApi
            ResourceId: !Ref FcplApiUserResource
            HttpMethod: GET
            AuthorizationType: AWS_IAM
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserFunction.Arn}/invocations
    FcplApiUserOptions:
        Type: "AWS::ApiGateway::Method"
        Properties:
            AuthorizationType: NONE
            RestApiId: !Ref FcplApi
            ResourceId: !Ref FcplApiUserResource
            HttpMethod: OPTIONS
            Integration:
                IntegrationResponses:
                    - StatusCode: 200
                      ResponseParameters:
                        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                        method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                      ResponseTemplates:
                        application/json: ''
                PassthroughBehavior: WHEN_NO_MATCH
                RequestTemplates:
                    application/json: '{"statusCode": 200}'
                Type: MOCK
            MethodResponses:
                - StatusCode: 200
                  ResponseModels:
                    application/json: 'Empty'
                  ResponseParameters:
                    method.response.header.Access-Control-Allow-Headers: false
                    method.response.header.Access-Control-Allow-Methods: false
                    method.response.header.Access-Control-Allow-Origin: false
    FcplApiDeployment:
        Type: "AWS::ApiGateway::Deployment"
        DependsOn:
            - FcplApiBooksGet
            - FcplApiBooksOptions
        Properties:
            RestApiId: !Ref FcplApi
            Description: Test deployment
    FcplApiStage:
        Type: "AWS::ApiGateway::Stage"
        Properties:
            StageName: test
            RestApiId: !Ref FcplApi
            DeploymentId: !Ref FcplApiDeployment
    GetBooksExecutionRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            Policies:
                - PolicyName: S3BucketAccess
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Effect: Allow
                          Action:
                            - "s3:GetObject"
                            - "s3:PutObject"
                          Resource: !Sub "arn:aws:s3:::${S3Bucket}/cache/*"
                        - Effect: Allow
                          Action:
                            - "s3:ListBucket"
                          Resource: !Sub "arn:aws:s3:::${S3Bucket}"
    GetBooksFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: !Ref S3Bucket
                S3Key: "functions/GetBooks/code.zip"
            Environment:
                Variables:
                    FCPLAccountId: !Ref FCPLAccountId
                    FCPLPassword: !Ref FCPLPassword
                    S3Bucket: !Ref S3Bucket
                    CachePrefix: "cache/TEST"
                    MaxCacheAgeHours: !Ref MaxCacheAgeHours
                    UserTableName: !Ref UserTable
            Handler: index.handler
            Role: !GetAtt GetBooksExecutionRole.Arn
            Runtime: nodejs6.10
            Timeout: 60
    GetBooksApiPermission:
        Type: "AWS::Lambda::Permission"
        Properties:
            Action: "lambda:InvokeFunction"
            FunctionName: !Ref GetBooksFunction
            Principal: "apigateway.amazonaws.com"
            SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FcplApi}/${FcplApiStage}/*/books"
    GetUserExecutionRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            Policies:
                - PolicyName: UserTableAccess
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Effect: Allow
                          Action:
                            - "dynamodb:GetItem"
                          Resource: !GetAtt UserTable.Arn
    GetUserFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: !Ref S3Bucket
                S3Key: "functions/GetUser/code.zip"
            Environment:
                Variables:
                    UserTableName: !Ref UserTable
            Handler: index.handler
            Role: !GetAtt GetUserExecutionRole.Arn
            Runtime: nodejs6.10
            Timeout: 60
    GetUserApiPermission:
        Type: "AWS::Lambda::Permission"
        Properties:
            Action: "lambda:InvokeFunction"
            FunctionName: !Ref GetUserFunction
            Principal: "apigateway.amazonaws.com"
            SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FcplApi}/${FcplApiStage}/*/user"
    AutoRenewerExecutionRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            Policies:
                - PolicyName: GetBooksInvokeAccess
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Effect: Allow
                          Action:
                            - "lambda:InvokeFunction"
                          Resource: !GetAtt GetBooksFunction.Arn
                - PolicyName: SNSTopicPublishAccess
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Effect: Allow
                          Action:
                            - "sns:Publish"
                          Resource: !Ref RenewalNotificationTopic
    AutoRenewerFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: !Ref S3Bucket
                S3Key: "functions/AutoRenewer/code.zip"
            Environment:
                Variables:
                    FCPLAccountId: !Ref FCPLAccountId
                    GetBooksFunctionName: !Ref GetBooksFunction
                    SNSTopicArn: !Ref RenewalNotificationTopic
            Handler: index.handler
            Role: !GetAtt AutoRenewerExecutionRole.Arn
            Runtime: nodejs6.10
            Timeout: 120
    AutoRenewerRulePermission:
        Type: "AWS::Lambda::Permission"
        Properties:
            Action: "lambda:InvokeFunction"
            FunctionName: !Ref AutoRenewerFunction
            Principal: "events.amazonaws.com"
            SourceArn: !GetAtt BackgroundRenewRule.Arn
    BackgroundRenewRule:
        Type: "AWS::Events::Rule"
        Properties:
            Description: !Sub "Renews books close to expiration every ${BackgroundRenewIntervalHours} hours"
            ScheduleExpression: !Sub "rate(${BackgroundRenewIntervalHours} hours)"
            State: ENABLED
            Targets:
                - Arn: !GetAtt AutoRenewerFunction.Arn
                  Id: RenewerFunctionScheduleTarget
    RenewalNotificationTopic:
        Type: "AWS::SNS::Topic"
        Properties:
            Subscription:
                - Endpoint: !Ref NotificationEmail
                  Protocol: email
Outputs:
    UserPoolProviderName:
        Value: !GetAtt UserPool.ProviderName
    UserPoolProviderURL:
        Value: !GetAtt UserPool.ProviderURL
    UserPoolId:
        Value: !Ref UserPool
    UserPoolArn:
        Value: !GetAtt UserPool.Arn
    UserPoolClientId:
        Value: !Ref UserPoolClient
    IdentityPoolId:
        Value: !Ref IdentityPool
    FcplApiEndpoint:
        Value: !Sub "https://${FcplApi}.execute-api.${AWS::Region}.amazonaws.com/${FcplApiStage}"
    GetBooksFunctionName:
        Value: !Ref GetBooksFunction
    GetUserFunctionName:
        Value: !Ref GetUserFunction
    AutoRenewerFunctionName:
        Value: !Ref AutoRenewerFunction
    Region:
        Value: !Ref AWS::Region
        
